language: php

php: 5.4

sudo: false

before_install:
  - XDEBUG_CONF=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - mv "$XDEBUG_CONF" "$XDEBUG_CONF".bak
  - composer self-update
  - if [[ -n $SATIS_PASSWORD ]]; then composer config http-basic.composer.ampersandweb.co.uk $SATIS_USERNAME $SATIS_PASSWORD; fi
  - if [[ -n $GITHUB_TOKEN ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

install:
  - composer install -o --no-interaction --prefer-dist

before_script: mv "$XDEBUG_CONF".bak "$XDEBUG_CONF"

script:
  - php vendor/bin/phpunit -c phpunit-vanilla-unit.xml;

cache:
  directories: $HOME/.composer/cache

after_success: bash <(curl -s https://codecov.io/bash)